### PR TITLE
Msim fixes

### PR DESCRIPTION
**Pull request by Thecrazyskull**

### CODE REVIEW

**Comment by ezio84** [comment]
Thanks!

**Comment by ezio84** [comment]
PS: the no sim icon in the statusbar can still be useful for someone, maybe it's better to not hide it.
Do you agree?

**Comment by Thecrazyskull** [comment]
Well since slim uses a whole other msim inplementation from cm its gonna be very hard to inplement settings toggle for it.
I own a msim device but i use only 1 sim (stupid me lol) and that 2nd icon was irritating me a lot so i got rid of it.
Ofcourse you can decide but i recommend you'll keep it :)

**Comment by ezio84** [comment]
Eheh ye if you always have the no-sim icon in the status bar then it's boring :D
On the Nexus instead it's still useful, i'll revert just that commit ;) Thanks for the fixes mate!!!

**Comment by Thecrazyskull** [comment]
Np, ill keep that commit local for now :)

**Comment by ezio84** [comment]
;) thanks again!

**Pull request merged**
